### ISSUE TITLE
[Feature] User login

### ISSUE THREAD

**Issue by tyrro** [tyrro/react-survey#12]
**Definition of Done**

- [x] https://github.com/tyrro/react-survey/issues/9
- [x] https://github.com/tyrro/react-survey/issues/10
- [x] https://github.com/tyrro/react-survey/issues/11
