### ISSUE TITLE
[Feature] User logout

### ISSUE THREAD

**Issue by tyrro** [tyrro/react-survey#15]
**Definition of Done**

- [x] https://github.com/tyrro/react-survey/issues/21
- [x] https://github.com/tyrro/react-survey/issues/13
- [x] https://github.com/tyrro/react-survey/issues/14
