### ISSUE TITLE
[Feature] Reset Password

### ISSUE THREAD

**Issue by tyrro** [tyrro/react-survey#19]
**Definition of Done**

- [x] https://github.com/tyrro/react-survey/issues/16
- [x] https://github.com/tyrro/react-survey/issues/17
- [x] https://github.com/tyrro/react-survey/issues/18
