### ISSUE TITLE
[Feature] Dashboard - Survey List 

### ISSUE THREAD

**Issue by tyrro** [tyrro/react-survey#27]
**Definition of Done**

- [x]  https://github.com/tyrro/react-survey/issues/23
- [x]  https://github.com/tyrro/react-survey/issues/24
- [x]  https://github.com/tyrro/react-survey/issues/25
- [x]  https://github.com/tyrro/react-survey/issues/26
- [x]  https://github.com/tyrro/react-survey/issues/28
