### ISSUE TITLE
[Chore] Setup project

### ISSUE THREAD

**Issue by tyrro** [tyrro/react-survey#7]
**Definition of Done**

- [x] https://github.com/tyrro/react-survey/issues/1
- [x] https://github.com/tyrro/react-survey/issues/3
- [x] https://github.com/tyrro/react-survey/issues/4
- [x] https://github.com/tyrro/react-survey/issues/5
- [x] https://github.com/tyrro/react-survey/issues/6
